version: 2

before:
  hooks:
    - go mod download

builds:
  - env:
      - GO111MODULE=on
      - CGO_ENABLED=0
      - GO_MODULENAME=github.com/golgoth31/release-installer
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    binary: ri
    ldflags:
      - -s
      - -w
      - -X "{{.Env.GO_MODULENAME}}/configs.Version={{.Tag}}"
      - -X "{{.Env.GO_MODULENAME}}/configs.Date={{.Date}}"
      - -X "{{.Env.GO_MODULENAME}}/configs.BuiltBy=goreleaser"

archives:
  - formats:
      - binary
    name_template: "{{ .Binary }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^Merge branch"

checksum:
  name_template: "ri_{{ .Tag }}_SHA256SUMS.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
