env:
  - GO111MODULE=on
  - CGO_ENABLED=0
  - GO_MODULENAME=github.com/golgoth31/release-installer
before:
  hooks:
    - go mod download
builds:
  - goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 7
    binary: ri
    ldflags:
      - -s
      - -w
      - -X "{{.Env.GO_MODULENAME}}/configs.Version={{.Tag}}"
      - -X "{{.Env.GO_MODULENAME}}/configs.Date={{.Date}}"
      - -X "{{.Env.GO_MODULENAME}}/configs.BuiltBy=goreleaser"
archives:
  - format: binary
    name_template: "{{ .Binary }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
checksum:
  name_template: "ri_{{ .Tag }}_SHA256SUMS.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^Merge branch"
