// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/release.proto

package release_proto

import (
	common "github.com/golgoth31/release-installer/pkg/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Release struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion    string                 `protobuf:"bytes,1,opt,name=apiVersion,proto3" json:"apiVersion,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Metadata      *common.Metadata       `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Spec          *Spec                  `protobuf:"bytes,4,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Release) Reset() {
	*x = Release{}
	mi := &file_proto_release_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Release) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Release) ProtoMessage() {}

func (x *Release) ProtoReflect() protoreflect.Message {
	mi := &file_proto_release_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Release.ProtoReflect.Descriptor instead.
func (*Release) Descriptor() ([]byte, []int) {
	return file_proto_release_proto_rawDescGZIP(), []int{0}
}

func (x *Release) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *Release) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Release) GetMetadata() *common.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Release) GetSpec() *Spec {
	if x != nil {
		return x.Spec
	}
	return nil
}

// Spec ...
type Spec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Os            string                 `protobuf:"bytes,2,opt,name=os,proto3" json:"os,omitempty"`
	Arch          string                 `protobuf:"bytes,3,opt,name=arch,proto3" json:"arch,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	Binary        string                 `protobuf:"bytes,5,opt,name=binary,proto3" json:"binary,omitempty"`
	Default       bool                   `protobuf:"varint,6,opt,name=default,proto3" json:"default,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Spec) Reset() {
	*x = Spec{}
	mi := &file_proto_release_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Spec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Spec) ProtoMessage() {}

func (x *Spec) ProtoReflect() protoreflect.Message {
	mi := &file_proto_release_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Spec.ProtoReflect.Descriptor instead.
func (*Spec) Descriptor() ([]byte, []int) {
	return file_proto_release_proto_rawDescGZIP(), []int{1}
}

func (x *Spec) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Spec) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *Spec) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *Spec) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Spec) GetBinary() string {
	if x != nil {
		return x.Binary
	}
	return ""
}

func (x *Spec) GetDefault() bool {
	if x != nil {
		return x.Default
	}
	return false
}

var File_proto_release_proto protoreflect.FileDescriptor

const file_proto_release_proto_rawDesc = "" +
	"\n" +
	"\x13proto/release.proto\x12\n" +
	"ri.release\x1a\x12proto/common.proto\"\x94\x01\n" +
	"\aRelease\x12\x1e\n" +
	"\n" +
	"apiVersion\x18\x01 \x01(\tR\n" +
	"apiVersion\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12/\n" +
	"\bmetadata\x18\x03 \x01(\v2\x13.ri.common.MetadataR\bmetadata\x12$\n" +
	"\x04spec\x18\x04 \x01(\v2\x10.ri.release.SpecR\x04spec\"\x8a\x01\n" +
	"\x04Spec\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x0e\n" +
	"\x02os\x18\x02 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x03 \x01(\tR\x04arch\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\x16\n" +
	"\x06binary\x18\x05 \x01(\tR\x06binary\x12\x18\n" +
	"\adefault\x18\x06 \x01(\bR\adefaultBHZFgithub.com/golgoth31/release-installer/pkg/proto/release;release_protob\x06proto3"

var (
	file_proto_release_proto_rawDescOnce sync.Once
	file_proto_release_proto_rawDescData []byte
)

func file_proto_release_proto_rawDescGZIP() []byte {
	file_proto_release_proto_rawDescOnce.Do(func() {
		file_proto_release_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_release_proto_rawDesc), len(file_proto_release_proto_rawDesc)))
	})
	return file_proto_release_proto_rawDescData
}

var file_proto_release_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_release_proto_goTypes = []any{
	(*Release)(nil),         // 0: ri.release.Release
	(*Spec)(nil),            // 1: ri.release.Spec
	(*common.Metadata)(nil), // 2: ri.common.Metadata
}
var file_proto_release_proto_depIdxs = []int32{
	2, // 0: ri.release.Release.metadata:type_name -> ri.common.Metadata
	1, // 1: ri.release.Release.spec:type_name -> ri.release.Spec
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_release_proto_init() }
func file_proto_release_proto_init() {
	if File_proto_release_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_release_proto_rawDesc), len(file_proto_release_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_release_proto_goTypes,
		DependencyIndexes: file_proto_release_proto_depIdxs,
		MessageInfos:      file_proto_release_proto_msgTypes,
	}.Build()
	File_proto_release_proto = out.File
	file_proto_release_proto_goTypes = nil
	file_proto_release_proto_depIdxs = nil
}
