// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/reference.proto

package reference_proto

import (
	common "github.com/golgoth31/release-installer/pkg/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Reference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion    string                 `protobuf:"bytes,1,opt,name=apiVersion,proto3" json:"apiVersion,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Metadata      *common.Metadata       `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Spec          *Spec                  `protobuf:"bytes,4,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reference) Reset() {
	*x = Reference{}
	mi := &file_proto_reference_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reference) ProtoMessage() {}

func (x *Reference) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reference_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reference.ProtoReflect.Descriptor instead.
func (*Reference) Descriptor() ([]byte, []int) {
	return file_proto_reference_proto_rawDescGZIP(), []int{0}
}

func (x *Reference) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *Reference) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Reference) GetMetadata() *common.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Reference) GetSpec() *Spec {
	if x != nil {
		return x.Spec
	}
	return nil
}

// Spec ...
type Spec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repo          *Repo                  `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	File          *File                  `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
	Checksum      *Checksum              `protobuf:"bytes,3,opt,name=checksum,proto3" json:"checksum,omitempty"`
	Available     *Available             `protobuf:"bytes,4,opt,name=available,proto3" json:"available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Spec) Reset() {
	*x = Spec{}
	mi := &file_proto_reference_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Spec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Spec) ProtoMessage() {}

func (x *Spec) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reference_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Spec.ProtoReflect.Descriptor instead.
func (*Spec) Descriptor() ([]byte, []int) {
	return file_proto_reference_proto_rawDescGZIP(), []int{1}
}

func (x *Spec) GetRepo() *Repo {
	if x != nil {
		return x.Repo
	}
	return nil
}

func (x *Spec) GetFile() *File {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *Spec) GetChecksum() *Checksum {
	if x != nil {
		return x.Checksum
	}
	return nil
}

func (x *Spec) GetAvailable() *Available {
	if x != nil {
		return x.Available
	}
	return nil
}

// File ...
type File struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Src           string                 `protobuf:"bytes,2,opt,name=src,proto3" json:"src,omitempty"`
	Binary        string                 `protobuf:"bytes,3,opt,name=binary,proto3" json:"binary,omitempty"`
	Mode          string                 `protobuf:"bytes,4,opt,name=mode,proto3" json:"mode,omitempty"`
	BinaryPath    string                 `protobuf:"bytes,5,opt,name=binaryPath,proto3" json:"binaryPath,omitempty"`
	Link          string                 `protobuf:"bytes,6,opt,name=link,proto3" json:"link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *File) Reset() {
	*x = File{}
	mi := &file_proto_reference_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reference_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_proto_reference_proto_rawDescGZIP(), []int{2}
}

func (x *File) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *File) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

func (x *File) GetBinary() string {
	if x != nil {
		return x.Binary
	}
	return ""
}

func (x *File) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *File) GetBinaryPath() string {
	if x != nil {
		return x.BinaryPath
	}
	return ""
}

func (x *File) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

// Checksum ...
type Checksum struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Check         bool                   `protobuf:"varint,1,opt,name=check,proto3" json:"check,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	File          string                 `protobuf:"bytes,3,opt,name=file,proto3" json:"file,omitempty"`
	Format        string                 `protobuf:"bytes,4,opt,name=format,proto3" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Checksum) Reset() {
	*x = Checksum{}
	mi := &file_proto_reference_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Checksum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Checksum) ProtoMessage() {}

func (x *Checksum) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reference_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Checksum.ProtoReflect.Descriptor instead.
func (*Checksum) Descriptor() ([]byte, []int) {
	return file_proto_reference_proto_rawDescGZIP(), []int{3}
}

func (x *Checksum) GetCheck() bool {
	if x != nil {
		return x.Check
	}
	return false
}

func (x *Checksum) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Checksum) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *Checksum) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

// Repo ...
type Repo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Owner         string                 `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Repo) Reset() {
	*x = Repo{}
	mi := &file_proto_reference_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Repo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Repo) ProtoMessage() {}

func (x *Repo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reference_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Repo.ProtoReflect.Descriptor instead.
func (*Repo) Descriptor() ([]byte, []int) {
	return file_proto_reference_proto_rawDescGZIP(), []int{4}
}

func (x *Repo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Repo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Repo) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

// Available ...
type Available struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Os            *Os                    `protobuf:"bytes,1,opt,name=os,proto3" json:"os,omitempty"`
	Arch          *Arch                  `protobuf:"bytes,2,opt,name=arch,proto3" json:"arch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Available) Reset() {
	*x = Available{}
	mi := &file_proto_reference_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Available) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Available) ProtoMessage() {}

func (x *Available) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reference_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Available.ProtoReflect.Descriptor instead.
func (*Available) Descriptor() ([]byte, []int) {
	return file_proto_reference_proto_rawDescGZIP(), []int{5}
}

func (x *Available) GetOs() *Os {
	if x != nil {
		return x.Os
	}
	return nil
}

func (x *Available) GetArch() *Arch {
	if x != nil {
		return x.Arch
	}
	return nil
}

// OS ...
type Os struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Linux         string                 `protobuf:"bytes,1,opt,name=linux,proto3" json:"linux,omitempty"`
	Windows       string                 `protobuf:"bytes,2,opt,name=windows,proto3" json:"windows,omitempty"`
	Darwin        string                 `protobuf:"bytes,3,opt,name=darwin,proto3" json:"darwin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Os) Reset() {
	*x = Os{}
	mi := &file_proto_reference_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Os) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Os) ProtoMessage() {}

func (x *Os) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reference_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Os.ProtoReflect.Descriptor instead.
func (*Os) Descriptor() ([]byte, []int) {
	return file_proto_reference_proto_rawDescGZIP(), []int{6}
}

func (x *Os) GetLinux() string {
	if x != nil {
		return x.Linux
	}
	return ""
}

func (x *Os) GetWindows() string {
	if x != nil {
		return x.Windows
	}
	return ""
}

func (x *Os) GetDarwin() string {
	if x != nil {
		return x.Darwin
	}
	return ""
}

// Arch ...
type Arch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	I386          string                 `protobuf:"bytes,1,opt,name=i386,proto3" json:"i386,omitempty"`
	Amd64         string                 `protobuf:"bytes,2,opt,name=amd64,proto3" json:"amd64,omitempty"`
	Arm64         string                 `protobuf:"bytes,3,opt,name=arm64,proto3" json:"arm64,omitempty"`
	Arm           string                 `protobuf:"bytes,4,opt,name=arm,proto3" json:"arm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Arch) Reset() {
	*x = Arch{}
	mi := &file_proto_reference_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Arch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Arch) ProtoMessage() {}

func (x *Arch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reference_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Arch.ProtoReflect.Descriptor instead.
func (*Arch) Descriptor() ([]byte, []int) {
	return file_proto_reference_proto_rawDescGZIP(), []int{7}
}

func (x *Arch) GetI386() string {
	if x != nil {
		return x.I386
	}
	return ""
}

func (x *Arch) GetAmd64() string {
	if x != nil {
		return x.Amd64
	}
	return ""
}

func (x *Arch) GetArm64() string {
	if x != nil {
		return x.Arm64
	}
	return ""
}

func (x *Arch) GetArm() string {
	if x != nil {
		return x.Arm
	}
	return ""
}

var File_proto_reference_proto protoreflect.FileDescriptor

const file_proto_reference_proto_rawDesc = "" +
	"\n" +
	"\x15proto/reference.proto\x12\fri.reference\x1a\x12proto/common.proto\"\x98\x01\n" +
	"\tReference\x12\x1e\n" +
	"\n" +
	"apiVersion\x18\x01 \x01(\tR\n" +
	"apiVersion\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12/\n" +
	"\bmetadata\x18\x03 \x01(\v2\x13.ri.common.MetadataR\bmetadata\x12&\n" +
	"\x04spec\x18\x04 \x01(\v2\x12.ri.reference.SpecR\x04spec\"\xc1\x01\n" +
	"\x04Spec\x12&\n" +
	"\x04repo\x18\x01 \x01(\v2\x12.ri.reference.RepoR\x04repo\x12&\n" +
	"\x04file\x18\x02 \x01(\v2\x12.ri.reference.FileR\x04file\x122\n" +
	"\bchecksum\x18\x03 \x01(\v2\x16.ri.reference.ChecksumR\bchecksum\x125\n" +
	"\tavailable\x18\x04 \x01(\v2\x17.ri.reference.AvailableR\tavailable\"\x8a\x01\n" +
	"\x04File\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x10\n" +
	"\x03src\x18\x02 \x01(\tR\x03src\x12\x16\n" +
	"\x06binary\x18\x03 \x01(\tR\x06binary\x12\x12\n" +
	"\x04mode\x18\x04 \x01(\tR\x04mode\x12\x1e\n" +
	"\n" +
	"binaryPath\x18\x05 \x01(\tR\n" +
	"binaryPath\x12\x12\n" +
	"\x04link\x18\x06 \x01(\tR\x04link\"^\n" +
	"\bChecksum\x12\x14\n" +
	"\x05check\x18\x01 \x01(\bR\x05check\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x12\n" +
	"\x04file\x18\x03 \x01(\tR\x04file\x12\x16\n" +
	"\x06format\x18\x04 \x01(\tR\x06format\"D\n" +
	"\x04Repo\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05owner\x18\x03 \x01(\tR\x05owner\"U\n" +
	"\tAvailable\x12 \n" +
	"\x02os\x18\x01 \x01(\v2\x10.ri.reference.OsR\x02os\x12&\n" +
	"\x04arch\x18\x02 \x01(\v2\x12.ri.reference.ArchR\x04arch\"L\n" +
	"\x02Os\x12\x14\n" +
	"\x05linux\x18\x01 \x01(\tR\x05linux\x12\x18\n" +
	"\awindows\x18\x02 \x01(\tR\awindows\x12\x16\n" +
	"\x06darwin\x18\x03 \x01(\tR\x06darwin\"X\n" +
	"\x04Arch\x12\x12\n" +
	"\x04i386\x18\x01 \x01(\tR\x04i386\x12\x14\n" +
	"\x05amd64\x18\x02 \x01(\tR\x05amd64\x12\x14\n" +
	"\x05arm64\x18\x03 \x01(\tR\x05arm64\x12\x10\n" +
	"\x03arm\x18\x04 \x01(\tR\x03armBLZJgithub.com/golgoth31/release-installer/pkg/proto/reference;reference_protob\x06proto3"

var (
	file_proto_reference_proto_rawDescOnce sync.Once
	file_proto_reference_proto_rawDescData []byte
)

func file_proto_reference_proto_rawDescGZIP() []byte {
	file_proto_reference_proto_rawDescOnce.Do(func() {
		file_proto_reference_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_reference_proto_rawDesc), len(file_proto_reference_proto_rawDesc)))
	})
	return file_proto_reference_proto_rawDescData
}

var file_proto_reference_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_reference_proto_goTypes = []any{
	(*Reference)(nil),       // 0: ri.reference.Reference
	(*Spec)(nil),            // 1: ri.reference.Spec
	(*File)(nil),            // 2: ri.reference.File
	(*Checksum)(nil),        // 3: ri.reference.Checksum
	(*Repo)(nil),            // 4: ri.reference.Repo
	(*Available)(nil),       // 5: ri.reference.Available
	(*Os)(nil),              // 6: ri.reference.Os
	(*Arch)(nil),            // 7: ri.reference.Arch
	(*common.Metadata)(nil), // 8: ri.common.Metadata
}
var file_proto_reference_proto_depIdxs = []int32{
	8, // 0: ri.reference.Reference.metadata:type_name -> ri.common.Metadata
	1, // 1: ri.reference.Reference.spec:type_name -> ri.reference.Spec
	4, // 2: ri.reference.Spec.repo:type_name -> ri.reference.Repo
	2, // 3: ri.reference.Spec.file:type_name -> ri.reference.File
	3, // 4: ri.reference.Spec.checksum:type_name -> ri.reference.Checksum
	5, // 5: ri.reference.Spec.available:type_name -> ri.reference.Available
	6, // 6: ri.reference.Available.os:type_name -> ri.reference.Os
	7, // 7: ri.reference.Available.arch:type_name -> ri.reference.Arch
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_proto_reference_proto_init() }
func file_proto_reference_proto_init() {
	if File_proto_reference_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_reference_proto_rawDesc), len(file_proto_reference_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_reference_proto_goTypes,
		DependencyIndexes: file_proto_reference_proto_depIdxs,
		MessageInfos:      file_proto_reference_proto_msgTypes,
	}.Build()
	File_proto_reference_proto = out.File
	file_proto_reference_proto_goTypes = nil
	file_proto_reference_proto_depIdxs = nil
}
