apiVersion: release/v1
kind: Release
metadata:
  name: istioctl
  web: https://istio.io/
spec:
  url: https://github.com/istio/istio/releases/download/{{ .Version }}
  file:
    name: istioctl-{{ .Version }}-{{ .Os }}-{{ .Arch }}.tar.gz
    binaryPath: "."
    binary: istioctl
  checksum:
    url: https://github.com/istio/istio/releases/download/{{ .Version }}
    file: istioctl-{{ .Version }}-{{ .Os }}-{{ .Arch }}.tar.gz.sha256
    format: sha256
