apiVersion: release/v1
kind: Release
metadata:
  name: terraform
  web: https://terraform.io/
spec:
  url: https://releases.hashicorp.com/terraform/{{ .Version }}
  file:
    name: terraform_{{ .Version }}_{{ .Os }}_{{ .Arch }}.zip
    binaryPath: terraform
  checksum:
    url: https://releases.hashicorp.com/terraform/{{ .Version }}
    file: terraform_{{ .Version }}_SHA256SUMS
    format: sha256
