apiVersion: release/v1
kind: Release
metadata:
  name: terraform
  web: https://terraform.io/
spec:
  url: https://releases.hashicorp.com/terraform/{{ .Version }}
  file:
    src: terraform_{{ .Version }}_{{ .Os }}_{{ .Arch }}.zip
    binaryPath: "."
    binary: terraform
    mode: archive
  checksum:
    url: https://releases.hashicorp.com/terraform/{{ .Version }}
    file: terraform_{{ .Version }}_SHA256SUMS
    format: sha256
  available:
    os:
      linux: linux
      darwin: darwin
      windows: windows
    arch:
      amd64: amd64
      i386: "386"
      arm64: arm64
